#!/usr/bin/python3
'''
class rectangle
'''

from models.base import Base


class Rectangle(Base):
    '''
    rectangle class that inherits from Base class
    '''
    def __init__(self, width, height, x=0, y=0, id=None):
        '''
        class constructor
        '''
        super().__init__(id)
        self.__width = width
        self.__height = height
        self.__x = x
        self.__y = y

    @property
    def width(self):
        '''
        gets the width attribute
        '''
        return self.__width

    @width.setter
    def width(self, value):
        '''
        sets width
        '''
        if not isinstance(value, int):
            raise TypeError("width must be an integer")
        elif value <= 0:
            raise ValueError("width must be > 0")
        self.__width = value

    @property
    def height(self):
        '''
        gets height
        '''
        return self.__height

    @height.setter
    def height(self, value):
        '''
        sets height
        '''
        if not isinstance(value, int):
            raise TypeError("height must be an integer")
        elif value <= 0:
            raise ValueError("height must be > 0")
        self.__height = value

    @property
    def x(self):
        '''
        gets x
        '''
        return self.__x

    @x.setter
    def x(self, value):
        '''
        sets x
        '''
        if not isinstance(value, int):
            raise TypeError("x must be an integer")
        elif value < 0:
            raise ValueError("x must be >= 0")
        self.__x = value

    @property
    def y(self):
        '''
        gets y
        '''
        return self.__y

    @y.setter
    def y(self, value):
        '''
        sets y
        '''
        if not isinstance(value, int):
            raise TypeError("y must be an integer")
        elif value < 0:
            raise ValueError("y must be >= 0")
        self.__y = value
